version: '3.8'

services:
  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./traffic-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/trafficdb
      - JWT_SECRET=secret1234
      - PORT=5000
    volumes:
      - ./traffic-backend/uploads:/app/uploads
    depends_on:
      - mongo

  frontend:
    build: ./traffic-frontend
    expose:
      - "3000"
    environment:
      - VITE_API_URL=https://nilemix.duckdns.org/api
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro          # ربط المجلد الحقيقي للشهادات
      - ./certbot/www:/var/www/certbot                 # مجلد ويبرووت للـ certbot لو محتاج
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data:

